# - name: Get new hostname
#   set_fact: new_hostname={{hostvars[inventory_hostname].vars.hostname}}

- name: Set hostname

  command: hostname
  register: old_hostname

- import_tasks: sethostname.yaml
  when: old_hostname.stdout != hostvars[inventory_hostname].vars.hostname
