# - name: Get new hostname
#   set_fact: new_hostname={{hostvars[inventory_hostname].vars.hostname}}

- name: Set hostname
  command: hostname
  register: old_hostname

- meta: end_play
  when: old_hostname.stdout == hostvars[inventory_hostname].vars.hostname

- debug: 
    msg: Change hostname from '{{old_hostname.stdout}}' to '{{hostvars[inventory_hostname].vars.hostname}}'

- command: hostnamectl set-hostname {{hostvars[inventory_hostname].vars.hostname}}
