---
- name: Install Apache
  apt: 
    name: apache2
    state: present

- name: Stop Apache
  service: 
    name: apache2
    state: stopped

- import_tasks: conf/charset.yaml
- import_tasks: conf/server-name.yaml

- import_tasks: sites/devserver.yaml

- name: Start Apache
  service: 
    name: apache2
    state: started


- name: Add record to ./etc.hosts
  block:
    - local_action: lineinfile path=./etc.hosts line="{{ ansible_host }}\t{{ hv_options.domain }}"
  rescue:
    - local_action: copy content="{{ ansible_host }}\t{{ hv_options.domain }}" dest=./etc.hosts
...