all:
  hosts:
    deb:
      ansible_host: 172.28.128.3
      ansible_port: 22
      ansible_user: root
      ansible_ssh_pass: 612284
      vars:
        hostname: dev
        locale: ru_RU.utf8
        timezone: Europe/Moscow