---
- name: Enabling locale {{ settings.locale.name }}
  replace:
    path: /etc/locale.gen
    regexp: '^#\s*({{ settings.locale.re_pattern }}.*)$'
    replace: '\1'
    backup: yes

- name: Generate locales
  shell: locale-gen

- name: Get new locale
  shell: localectl list-locales | grep -i -E '{{ settings.locale.grep_pattern }}'
  register: ds_new_locale

- name: Set locale {{ ds_new_locale.stdout }}
  shell: localectl set-locale LANG={{ ds_new_locale.stdout }}
...