---
- name: Uncomment /etc/locale.gen for {{ gv_options.locale.name}}
  replace:
    path: /etc/locale.gen
    regexp: '^#\s*({{ gv_options.locale.pattern }}.*)$'
    replace: '\1'
  
- name: Generate locales
  shell: locale-gen
...