---
- name: Get current locale
  shell: localectl status
  register: _locale

- set_fact:
    _is_locale: "{{ _locale.stdout | regex_search(gv_options.locale.pattern) }}"

- import_tasks: setlocale.yaml
  when: _is_locale == ""
...