---
- name: Install phpMyAdmin
  apt: 
    name: phpmyadmin
    state: present

- name: Stop Apache
  service:
    name: apache2
    state: stopped

- name: Add site configuration phpmyadmin.conf
  template: 
    src: ../templates/sites/phpmyadmin.conf
    dest: /etc/apache2/sites-available/phpmyadmin.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Enable phpmyadmin.{{ settings.hostname }}.dev
  shell: a2ensite phpmyadmin

- name: Start Apache
  service:
    name: apache2
    state: started

- name: Add record to ./etc.hosts
  block:
    - local_action: lineinfile path=./etc.hosts line="{{ ansible_host }}\tphpmyadmin.{{ hv_options.domain }}"
  rescue:
    - local_action: copy content="{{ ansible_host }}\tphpmyadmin.{{ hv_options.domain }}" dest=./etc.hosts

...