all:
  hosts:
  children:
    devserver:
      hosts:
        debian:
          ansible_host: 172.28.128.3
          ansible_port: 22
          ansible_user: root
          ansible_ssh_private_key_file: configs/vagrant-debian-root
          