---
- name: Create network user '{{ mysql.network_user.name }}'
  template:
    src: ../templates/network-user.sql
    dest: /root/network-user.sql
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Apply network-user.sql
  shell: mysql -u root -p{{ mysql.root_password }} < /root/network-user.sql
  ignore_errors: yes

- name: Remove network-user.sql
  file: 
    path: /root/network-user.sql
    state: absent
...