---
- name: Create mysql-init file
  template:
    src: ../templates/mysql-init
    dest: /root/mysql-init
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Start mysql-init file
  shell: mysqld_safe --init-file=/root/mysql-init &

- pause:
    prompt: Waiting ...
    seconds: 1

- name: Remove mysql-init file
  file: 
    path: /root/mysql-init
    state: absent
...