---
- name: Set hostname {{ settings.hostname }}
  command: hostnamectl set-hostname {{ settings.hostname }}

- name: Replace hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '\b{{ ds_old_hostname.stdout }}\b'
    replace: '{{ settings.hostname }}'
    backup: yes
...