---
- name: Set hostname
  command: hostnamectl set-hostname {{ ds_hostname }}

- name: Replace hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '\b{{ ds_old_hostname.stdout }}\b'
    replace: '{{ ds_hostname }}'
    backup: yes
...