---
- name: Set hostname {{ hv_options.host }}
  command: hostnamectl set-hostname {{ hv_options.host }}

- name: Replace hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: '\b{{ _hostname.stdout }}\b'
    replace: '{{ hv_options.host }}'
...