---
- name: Get timezone
  shell: timedatectl status | grep '{{ settings.timezone }}'
  register: ds_timezone_present
  ignore_errors: true

- import_tasks:
    timedatectl.yaml
  when: ds_timezone_present.stdout == ""

...