---
- name: Get timezone
  shell: timedatectl status
  register: _timezone

- set_fact:
    _timezone: "{{ _timezone.stdout | regex_search(gv_options.timezone) }}"

- import_tasks: settimezone.yaml
  when: _timezone == ""

...