---
- name: Install PHP
  apt: name={{ item }} state=present
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql

# - name: Stop MySQL
#   service:
#     name: mysql
#     state: stopped

# - import_tasks: allow-network.yaml
# - import_tasks: set-root-password.yaml

# - name: Start MySQL
#   service:
#     name: mysql
#     state: started

# - import_tasks: network-user.yaml
...